### PR TITLE
ci: Port CI to GitHub Actions

### PR DESCRIPTION
**Pull request by jan-auer**
Moves all CI jobs from Travis and AppVeyor to GitHub Actions. This comes with a few changes in the build pipeline:

- Python linting and formatting is checked again
- The macOS wheel now requires 10.15.0 since this is the minimum version offered by GitHub
- Integration tests no longer run haproxy or gobetween. They can be added as service if they provide any value.

Due to the wheel change, this will require a changelog entry.

### CODE REVIEW

File: .github/workflows/ci.yml [hunk 1]
```diff
@@ -79,6 +128,7 @@ jobs:
 
   event_schema:
     name: Event Schema
+    if: "!startsWith(github.ref , 'refs/heads/release')"
```
Comment (untitaker) [inline .github/workflows/ci.yml]: I assume we want to avoid rebuilding for no purpose when releasing but I would just keep it if it doesn't hurt (unless this builds on all platforms for whatever reason?)

**Review by untitaker — APPROVED** [review]

File: .github/workflows/ci.yml (hunk 1 above)
Comment (jan-auer) [reply .github/workflows/ci.yml]: This only builds on ubuntu-latest, but I'm trying to cut down on all non-essential jobs to make releases more reliable since they are unattended. Was even thinking of skipping lints.

**Comment by jan-auer** [comment]
For some reason, macOS is failing now, where it already passed in 312845fcdc0530a21e5f95fff5e4f3820a61056d. Since it complains that `serde_derive` is missing, I'm assuming that caches are somehow broken.

```
error[E0463]: can't find crate for `serde_derive` which `serde` depends on
##[error] --> relay-redis/src/config.rs:1:5
  |
1 | use serde::{Deserialize, Serialize};
  |     ^^^^^ can't find crate
```

File: .github/workflows/build.yml [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+
+  # TODO: Only push
+  pull_request:
+
+jobs:
+  linux:
+    name: Linux
+    runs-on: ubuntu-latest
+
+    # Only build on binary release branches
```
Comment (BYK) [inline .github/workflows/build.yml]:
```suggestion
    # Only build binary on release branches
```

File: .github/workflows/build.yml [hunk 3]
```diff
@@ -0,0 +1,130 @@
...
+
+      - uses: actions/setup-node@v1
+
+      - name: Upload to Zeus
+        env:
+          ZEUS_API_TOKEN: ${{ secrets.ZEUS_API_TOKEN }}
+          ZEUS_HOOK_BASE: ${{ secrets.ZEUS_HOOK_BASE }}
+        run: |
+          npm install -D @zeus-ci/cli
+          npx zeus job update -b $GITHUB_RUN_ID -j $GITHUB_RUN_NUMBER -r $GITHUB_SHA
```
Comment (BYK) [inline .github/workflows/build.yml]: If you are using `npx`, then you don't need `npm install -D @zeus-cli/cli` above. Additionally, you may wanna use `actions/cache` to skip the installation step.

File: .github/workflows/build.yml [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+          npx zeus upload -b $GITHUB_RUN_ID -j $GITHUB_RUN_NUMBER -t "application/octet-stream" -n relay-Linux-x86_64 target/x86_64-unknown-linux-gnu/release/relay
```
Comment (BYK) [inline .github/workflows/build.yml]: If these are large files, we may consider running the two upload commands in parallel.

File: .github/workflows/build.yml [hunk 5]
```diff
@@ -0,0 +1,130 @@
...
+          npx zeus upload -b $GITHUB_RUN_ID -j $GITHUB_RUN_NUMBER -t "application/octet-stream" -n relay-Linux-x86_64-debug.zip relay-debug.zip
+          npx zeus job update --status=passed -b $GITHUB_RUN_ID -j $GITHUB_RUN_NUMBER -r $GITHUB_SHA
+
+  macos:
+    name: macOS
+    runs-on: macos-10.15
+
+    # Only build on binary release branches
```
Comment (BYK) [inline .github/workflows/build.yml]:
```suggestion
    # Only build binary on release branches
```

File: .github/workflows/ci.yml [hunk 6]
```diff
@@ -98,50 +120,92 @@ jobs:
...
+          profile: minimal
+          override: true
 
-      - name: Deploy
-        if: github.ref == 'refs/heads/master'
+      - uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Install Dependencies
```
Comment (BYK) [inline .github/workflows/ci.yml:172]: Why not move this after the `actions/cache` step so it is also cached?

Comment (BYK) [reply .github/workflows/ci.yml:172]: Btw protip: you can skip entire steps based on the `action/cache` step's output: https://github.com/getsentry/sentry-docs/pull/2231

File: .github/workflows/ci.yml [hunk 7]
```diff
@@ -98,50 +120,92 @@ jobs:
...
+        image: confluentinc/cp-zookeeper
+        env:
+          ZOOKEEPER_CLIENT_PORT: 2181
+
+      kafka:
+        image: confluentinc/cp-kafka
+        env:
+          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
+          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
+          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
```
Comment (BYK) [inline .github/workflows/ci.yml:214]: You may want to apply the changes from https://github.com/getsentry/sentry/pull/20780 here

File: .github/workflows/deploy.yml [hunk 8]
```diff
@@ -0,0 +1,163 @@
+name: Deploy
+
+on:
```
Comment (BYK) [inline .github/workflows/deploy.yml:3]: You may wanna add `workflow_dispatch` here for manual triggers too

File: .github/workflows/deploy.yml [hunk 9]
```diff
@@ -0,0 +1,163 @@
...
+  push:
+    branches:
+      - master
+
+  # Run actions on PRs, but only deploy on master
+  pull_request:
```
Comment (BYK) [inline .github/workflows/deploy.yml:9]: Are you sure this doesn't deploy on PRs?

File: .github/workflows/deploy.yml [hunk 10]
```diff
@@ -0,0 +1,163 @@
...
+          args: -p generate-schema -- -o event.schema.json
+
+      - name: Deploy
+        if: github.ref == 'refs/heads/master'
+        env:
+          GITHUB_TOKEN: ${{ secrets.DATA_SCHEMAS_GITHUB_TOKEN }}
+        run: |
+          git config --global user.name "$(git log -1 --pretty=format:%an $GITHUB_SHA)"
+          git config --global user.email "$(git log -1 --pretty=format:%ae $GITHUB_SHA)"
+          git clone https://getsentry-bot:$GITHUB_TOKEN@github.com/getsentry/sentry-data-schemas
```
Comment (BYK) [inline .github/workflows/deploy.yml:83]: I think this part can/should be replaced with `actions/checkout`

File: .github/workflows/build.yml (hunk 2 above)
Comment (jan-auer) [reply .github/workflows/build.yml]: That's actually intended. There are "binary release branches" and "library release branches".

File: .github/workflows/build.yml (hunk 3 above)
Comment (jan-auer) [reply .github/workflows/build.yml]: Unfortunately, I do. The problem is that one cannot run `npx zeus` does not work as the package is named differently, so one would have to run `npx -p @zeus-ci/cli zeus`. But as soon as you use the `-p|--package` flag, it no longer uses cached installations and instead reinstalls on every invocation. The accepted workaround is to install like this and then use npx to invoke.

Comment (jan-auer) [reply .github/workflows/build.yml]: I looked into caching, too, but the installation only takes a few seconds, so even the overhead of the cache action is already larger.

File: .github/workflows/build.yml (hunk 4 above)
Comment (jan-auer) [reply .github/workflows/build.yml]: Here, too, uploads are super fast, so no need to parallelize. The largest file we're uploading across all builds is 50MB at the moment.

File: .github/workflows/ci.yml (hunk 6 above)
Comment (jan-auer) [reply .github/workflows/ci.yml:172]: We're not caching toolchain installations, only cargo's own cache and the target folder. These are the expensive operations that take time. All the rest is usually so fast that caching doesn't really matter and I opted to reduce caches to the absolute minimum.

FWIW, you can see that release builds don't have caches at all, to ensure we're never working off a poisoned cache.

File: .github/workflows/ci.yml (hunk 7 above)
Comment (jan-auer) [reply .github/workflows/ci.yml:214]: Thanks, that's a good hint! I'll add `KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS`. We can skip setting the log retention as the service and its volumes never live longer than a few minutes.

Comment (jan-auer) [reply .github/workflows/ci.yml:214]: I'm actually realizing that our test setup manually ensures a single partition already in application code since I didn't know about that setting. Still adding this as another layer of protection 👍

File: .github/workflows/deploy.yml (hunk 8 above)
Comment (jan-auer) [reply .github/workflows/deploy.yml:3]: Can do, what would be the use case for a manual trigger?

File: .github/workflows/deploy.yml (hunk 9 above)
Comment (jan-auer) [reply .github/workflows/deploy.yml:9]: Yes, the deploy steps in the jobs below are skipped when the ref is not master. Note that these jobs already run in master, it just moved to a new file.

File: .github/workflows/deploy.yml (hunk 10 above)
Comment (jan-auer) [reply .github/workflows/deploy.yml:83]: Sounds good, I'll consider that in a follow-up PR. These jobs were just moved, so I would like to not touch them. 

My plan is to make this a reusable action that we can use for all sorts of cross-committing activities we do in the organization.

File: .github/workflows/ci.yml (hunk 6 above)
Comment (BYK) [reply .github/workflows/ci.yml:172]: >FWIW, you can see that release builds don't have caches at all, to ensure we're never working off a poisoned cache.

I don't think poitioned caches are a significant thread but even if they were, we can simply make the caching step conditional on this not being a release branch and speed up PR builds?

File: .github/workflows/deploy.yml (hunk 9 above)
Comment (BYK) [reply .github/workflows/deploy.yml:9]: Ah, yes sorry I missed that check.

File: .github/workflows/deploy.yml (hunk 8 above)
Comment (BYK) [reply .github/workflows/deploy.yml:3]: Just in case something went wrong during the push or to force a new deploy over at the target repos but I guess you can simply re-run the job if something goes wrong.

**Comment by jan-auer** [comment]
This is ready now. Will disable AppVeyor and update status checks just before merging and then push the changelog to trigger the final build.

File: .github/workflows/build_binary.yml [hunk 11]
```diff
@@ -0,0 +1,116 @@
+name: Binary Release Build
+
+on:
+  push:
+    branches:
+      - release/**
+
+jobs:
+  linux:
```
Comment (billyvg) [inline .github/workflows/build_binary.yml:9]: You could use a [matrix](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) here, but tbh what you have is probably more clear despite some duplication

**Review by billyvg — COMMENTED** [review]
lgtm!

File: .github/workflows/build_binary.yml [hunk 12]
```diff
@@ -0,0 +1,116 @@
...
+        run: zip -r relay-dsym.zip target/release/relay.dSYM
+
+      - uses: actions/setup-node@v1
+
+      - name: Upload to Zeus
+        env:
+          ZEUS_API_TOKEN: ${{ secrets.ZEUS_API_TOKEN }}
+          ZEUS_HOOK_BASE: ${{ secrets.ZEUS_HOOK_BASE }}
+        run: |
+          npm install -D @zeus-ci/cli
```
Comment (untitaker) [inline .github/workflows/build_binary.yml:72]: out of curiosity, what was wrong with `install -g` and running the binary directly?

File: .appveyor.yml [hunk 13]
```diff
@@ -1,70 +0,0 @@
...
-  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
-  - rustc -vV
-  - cargo -vV
-  # Check out submodules
-  - git submodule update --init --recursive
-
-on_success:
-  - zeus job update --status=passed || echo "%$APPVEYOR_REPO_BRANCH%" | findstr /V "release/">nul
-
-on_failure:
```
Comment (untitaker) [inline .appveyor.yml:66]: on_failure does not seem to be ported, is there no equivalent on gha?

File: .github/workflows/deploy.yml [hunk 14]
```diff
@@ -0,0 +1,163 @@
...
+            ~/.cargo/registry
+            ~/.cargo/git
+            target
+          key: doc-${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
+
+      - run: make doc
+
+      - name: Deploy
+        if: github.ref == 'refs/heads/master'
+        uses: peaceiris/actions-gh-pages@v3
```
Comment (untitaker) [inline .github/workflows/deploy.yml:41]: this has come up before but do we have a general policy wrt third-party github actions? since github tags are mutable as opposed to most package registries, and this has access to a token

File: Cargo.toml [hunk 15]
```diff
@@ -2,5 +2,12 @@
 members = ["relay", "relay-*", "tools/*"]
 default-members = ["relay"]
 
+[profile.dev]
```
Comment (untitaker) [inline Cargo.toml:5]: This seems like counterintuitive behavior. Do we want to start doing this across the org?

**Review by untitaker — APPROVED** [review]
Do we really want to stop using the makefile entirely in CI? That creates a split between local dev and it.

File: .appveyor.yml (hunk 13 above)
Comment (BYK) [reply .appveyor.yml:66]: There is: https://github.com/getsentry/onpremise/blob/21d1b6d42eee14d0de93ba77fe981f9f2a82447e/.github/workflows/test.yml#L38-L42

File: .github/workflows/build_binary.yml (hunk 11 above)
Comment (jan-auer) [reply .github/workflows/build_binary.yml:9]: Good point. I had a matrix at first, but ended up choosing this for the cleaner config. As soon as `craft` supports GitHub artifacts, the biggest chunk of duplication (zeus uploads) will be gone and this will be neat and clean. Would propose to revisit once we can move off Zeus.

File: .appveyor.yml (hunk 13 above)
Comment (jan-auer) [reply .appveyor.yml:66]: Also, we no longer need this, as we do not depend on Zeus for status checks. It is only an artifact storage, so it does not matter whether we report failures.

File: .github/workflows/build_binary.yml (hunk 12 above)
Comment (jan-auer) [reply .github/workflows/build_binary.yml:72]: Good point, I can try that. Originally, I used just `npx`, and then noticed that it is reinstalling on every invocation. On Azure Pipelines, one cannot run global installations, but that may work on GitHub actions.

File: .github/workflows/deploy.yml (hunk 14 above)
Comment (jan-auer) [reply .github/workflows/deploy.yml:41]: Deferring to the policy-makers here. So far, there has been no push-back. 

Note that this was not changed from master, just moved.

File: Cargo.toml (hunk 15 above)
Comment (jan-auer) [reply Cargo.toml:5]: I think we should do this only where it shows significant benefits. I can imagine doing this in symbolicator, although there stack traces are actually useful for debugging in contrast to Relay. Repositories like `symbolic` or even smaller crates build fast enough so that such a hack is not necessary.

For the curious: This cuts build times in half, and reduces the size of the target folder by 45%.

File: .github/workflows/deploy.yml (hunk 14 above)
Comment (jan-auer) [reply .github/workflows/deploy.yml:41]: Maybe @billyvg has insights?

**Comment by jan-auer** [comment]
Here are two test releases with craft:

- Library run: https://github.com/getsentry/relay/runs/1142528497
- Library artifacts: https://zeus.ci/gh/getsentry/relay/builds/7793
- Binary run: https://github.com/getsentry/relay/runs/1142527218
- Binary artifacts: https://zeus.ci/gh/getsentry/relay/builds/7795/artifacts

**Comment by jan-auer** [comment]
This will require https://github.com/getsentry/craft/pull/124 for successful publishing with craft. Once we've released a patch release of craft, we need to bump the minimum craft requirement in `craft.yml` and then this can be merged.
